# SPDX-License-Identifier: GPL-2.0

target_y := bin

obj_y := core.o
obj_y += memset.o
obj_y += memcpy.o
obj_y += string.o
obj_y += mm.o
obj_y += sbi.o
obj_y += module.o
obj_y += init.o

extra_y := startup.lds
elf_lds := startup.lds
